# Rendu - Data Paper SNCF 
Nous avons été chargées d'analyser le jeu de données concernant les objets trouvés sur le réseau SNCF et de déterminer un angle de recherche. Nous avons choisi de découvrir quelle gare en France avait enregistré le plus grand nombre d'objets perdus. Après avoir défini notre angle, nous avons formulé l'hypothèse selon laquelle il s'agirait probablement de la gare de Paris Montparnasse, étant la plus grande gare de Paris. Afin de vérifier notre hypothèse, nous avons commencé par scruter le jeu de données du réseau SNCF pour analyser les valeurs existantes. Par la suite, nous avons identifié certaines valeurs superflues, notamment la colonne "Code UIC" composée exclusivement de chiffres. De plus, la colonne renfermant les dates et heures de restitution a été éliminée en raison de son caractère incomplet et de son inadéquation avec notre perspective. Enfin, la colonne "objets trouvés" a été supprimée en raison de l'uniformité de ses valeurs.
Après avoir défini notre point de vue, nous nous sommes focalisés sur la colonne "Gare" pour compter le nombre d'occurrences. Cette opération a été exécutée à l'aide de la formule `=NB.SI(B2:850243;"Paris Montparnasse")`. Nous avons ainsi sélectionné la colonne comportant les noms des gares en France, en dissociant par exemple la Gare Montparnasse, pour déterminer le nombre d'occurrences d'objets trouvés spécifiquement dans cette gare. Cette formule a été appliquée de manière itérative pour identifier toutes les occurrences d'objets trouvés dans les gares de Paris, puis dans les autres grandes gares de France.
Après avoir obtenu nos résultats, nous avons élaboré un tableau pour offrir une visualisation plus claire de nos nouvelles données, initialement exprimées en chiffres, comme par exemple les 47 078 objets trouvés à la Gare du Nord à Paris. Toutefois, nous avons constaté que ces chiffres ne communiquaient pas efficacement dans un tableau. C'est pourquoi, après avoir réfléchi collectivement, nous avons décidé de calculer la proportion du résultat en pourcentage à l'aide de la formule : `=nombre/total*100`. Pour la Gare du Nord, cela nous a permis d'obtenir un pourcentage de 13,68%. Grâce à ces pourcentages, nous avons créé deux graphiques en barres. Le premier se focalise sur le nombre d'objets trouvés dans les gares de Paris, tandis que le second se concentre sur les objets trouvés dans ce que nous considérons comme les plus grandes gares de France, telles que Marseille Saint-Charles ou Lyon Part-Dieu.
## Classement en pourcentage d’objets trouvés en gares de Paris
[Graphique : pourcentage d’objets trouvés en gares de Paris ](Ce PC/Télécharment/chart(4).png)
### Classement en pourcentage d’objets trouvés dans les plus grandes gares de France
[Graphique : pourcentage d’objets trouvés dans les plus grandes gares de France ](Ce PC/Télécharment/chart(2).png)
À la suite de notre analyse basée sur le jeu de données, nous pouvons confirmer que notre hypothèse initiale était incorrecte. Contrairement à notre supposition selon laquelle la Gare Montparnasse occuperait la première place, il s'avère que c'est la Gare de Lyon qui émerge comme la gare parisienne affichant le plus grand nombre d'objets trouvés, représentant un pourcentage de 25%. Cette gare joue un rôle crucial en tant que point de connexion entre les régions Rhône-Alpes et la Méditerranée, ainsi qu'avec d'autres destinations européennes comme l'Italie et l'Allemagne.
En seconde position, la Gare de Paris Montparnasse est légèrement devancée par la Gare de Lyon, affichant près de 24% d'objets trouvés, soit une différence minime de seulement 1%. Cette observation s'explique par le fait que la Gare Montparnasse, bien que la plus étendue de Paris, attire un nombre considérable de voyageurs et de passants en raison de ses liaisons rapides avec de nombreuses grandes villes françaises, telles que Bordeaux, Rennes et Poitiers, par exemple.
Enfin, la troisième gare présentant un nombre significatif d'objets trouvés est la Gare du Nord, accueillant près de 700 000 voyageurs quotidiennement en tant que hub international. Elle dessert non seulement des destinations françaises telles que Lille, mais aussi des gares au Royaume-Uni et aux Pays-Bas, la hissant ainsi au rang de la gare la plus fréquentée de France en 2023. Le pourcentage d'objets trouvés atteint alors près de 18%, représentant une différence de seulement 7% par rapport à la Gare de Lyon et de 6% de moins que la Gare Montparnasse.
En France, les quatre premières gares affichant le plus grand nombre d'objets trouvés sont parisiennes, puis la Gare Bordeaux St-Jean suit avec 9% d'objets retrouvés. Cette différence notable peut être attribuée au flux important de voyageurs entre la capitale et Bordeaux. Ensuite, Marseille se positionne juste derrière avec 8.5% d'objets trouvés, représentant une légère diminution de 0.5% par rapport à Bordeaux Saint Jean. Notons que les pourcentages entre les autres gares de France présentent une proximité, avec seulement 1 ou 2% d'écart.
Il nous semblait intéressant de constater que la Gare ayant le moins d'objets trouvés à Paris est également celle qui détient le plus bas pourcentage en France, à savoir la gare Massy TGV, avec seulement 1% d'objets retrouvés.  

En guise de conclusion, nous avons observé que notre hypothèse initiale était incorrecte. Malgré le fait que la gare Montparnasse soit la plus grande de France, elle n'est pas celle où l'on retrouve le plus grand nombre d'objets perdus. En réalité, c'est la gare de Lyon qui détient ce titre dans le réseau SNCF. Pour des recherches futures, il serait intéressant d'explorer quels sont les objets les plus fréquemment retrouvés dans les gares parisiennes.

#### Références
[Notre feuille de calcul](https://docs.google.com/spreadsheets/d/1-3Z1WeTDAUHC4d22L4gZi1FDB2kuX7iO6xagjvrcsok/edit#gid=1798325739)





